name: Deploy DEV

on:
  [workflow_dispatch]
  
jobs:
  DeployClient:
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        working-directory: .
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: Create env file
        run: echo ${{ secrets.FRONTEND_ENVFILE }} | base64 --decode > .env
      
      - run: yarn
      - run: CI=false yarn build
  
      - uses: 'google-github-actions/auth@v0'
        with:
          
          # Credentials stored inside WDCC organisation secrets
          credentials_json: '${{ secrets.UADS_GCP_DEPLOYMENT_SA_CREDENTIALS }}'

      - uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
        
          # Build path (path is excluded due to parent: false flag)
          path: 'web-build'
          parent: false
          
          # Bucket to add contents into
          destination: 'uads-dev.wdcc.co.nz'

  DeployBackend:
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        working-directory: .
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
        
      # Takes a secret (in base64 format) from github secrets, decodes it, and outputs to a file in private keys
      - name: Create private_keys and directory
        run: mkdir private_keys && echo ${{ secrets.APP_GA_CREDENTIALS }} | base64 --decode > private_keys/wdcc-uads-dev-9d43138b5371.json
      
      - name: Create env file
        run: echo ${{ secrets.BACKEND_ENVFILE }} | base64 --decode > gae_env.yaml
      
      - run: yarn

      - uses: 'google-github-actions/auth@v0'
        with:
          
          # Credentials stored inside WDCC organisation secrets
          credentials_json: '${{ secrets.UADS_GCP_DEPLOYMENT_SA_CREDENTIALS }}'

      - name: Run build script
        run: yarn build

      - id: 'app-engine-deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          project_id: wdcc-uads-dev
          working_directory: .
